id: bring_your_own_data_qna
name: Bring Your Own Data QnA
inputs:
  question:
    type: string
    default: How to use SDK V2?
    is_chat_input: false
outputs:
  output:
    type: string
    reference: ${answer_the_question_with_context.output}
nodes:
- name: lookup
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://ai-yamamuraaistudio222461227618.openai.azure.com/
        api_type: Azure
        api_version: 2023-07-01-preview
        batch_size: '16'
        connection:
          id: 
            /subscriptions/7c0e7310-204b-4ebe-8a85-e1fe4ec84a3c/resourceGroups/yamamura_aistudio/providers/Microsoft.MachineLearningServices/workspaces/yamamura-7924/connections/Default_AzureOpenAI
        connection_type: workspace_connection
        deployment: text-embedding-ada-002
        dimension: 1536
        file_format_version: '2'
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: 2023-07-01-preview
        connection:
          id: 
            /subscriptions/7c0e7310-204b-4ebe-8a85-e1fe4ec84a3c/resourceGroups/yamamura_aistudio/providers/Microsoft.MachineLearningServices/workspaces/yamamura-7924/connections/ai-search-aistudio-AzureAISearch-96m7z4vdh3-shared
        connection_type: workspace_connection
        endpoint: https://ai-search-aistudio.search.windows.net
        engine: azure-sdk
        field_mapping:
          content: content
          embedding: contentVector
          filename: filepath
          metadata: meta_json_string
          title: title
          url: url
        index: 20240322-index
        kind: acs
        semantic_configuration_name: azureml-default
      self:
        path: 
          azureml://subscriptions/7c0e7310-204b-4ebe-8a85-e1fe4ec84a3c/resourcegroups/yamamura_aistudio/workspaces/yamamura-7924/datastores/workspaceblobstore/paths/azureml/dda2c17d-305e-44ce-b214-e350448d99a0/index/
        asset_id: 
          azureml://locations/japaneast/workspaces/4690191f-cf4e-4930-b2bf-11a7158ece51/data/20240322-index/versions/1
    queries: ${inputs.question}
    query_type: Hybrid (vector + keyword)
    top_k: 2
  use_variants: false
- name: generate_prompt_context
  type: python
  source:
    type: code
    path: generate_prompt_context.py
  inputs:
    search_result: ${lookup.output}
  use_variants: false
- name: Prompt_variants
  use_variants: true
- name: answer_the_question_with_context
  type: llm
  source:
    type: code
    path: answer_the_question_with_context.jinja2
  inputs:
    deployment_name: ""
    temperature: 0
    top_p: 1
    max_tokens: 1000
    presence_penalty: 0
    frequency_penalty: 0
    suffix: ""
    echo: false
    best_of: 1
    prompt_text: ${Prompt_variants.output}
  provider: AzureOpenAI
  connection: ""
  api: chat
  module: promptflow.tools.aoai
  use_variants: false
node_variants:
  Prompt_variants:
    default_variant_id: variant_0
    variants:
      variant_0:
        node:
          name: Prompt_variants
          type: prompt
          source:
            type: code
            path: Prompt_variants.jinja2
          inputs:
            contexts: ${generate_prompt_context.output}
            question: ${inputs.question}
      variant_1:
        node:
          name: Prompt_variants
          type: prompt
          source:
            type: code
            path: Prompt_variants__variant_1.jinja2
          inputs:
            contexts: ${generate_prompt_context.output}
            question: ${inputs.question}
      variant_2:
        node:
          name: Prompt_variants
          type: prompt
          source:
            type: code
            path: Prompt_variants__variant_2.jinja2
          inputs:
            contexts: ${generate_prompt_context.output}
            question: ${inputs.question}
environment:
  python_requirements_txt: requirements.txt
